### ISSUE TITLE
Error: Method not found: Pchp.Core.PhpString Pchp.Library.PhpPath.file_get_contents

### ISSUE THREAD

**Issue by AdwardNguyen** [gordon-matt/peachpie-responsive-file-manager#1]
Hi, I just research your project and I try embed with my project but when I start, it's raise up an error.
Please help me! Thank you!

<img width="294" alt="screen shot 2018-10-03 at 2 09 59 pm" src="https://user-images.githubusercontent.com/22392606/46395569-f8ab8b80-c716-11e8-9352-6e19d709d1fa.png">
<img width="1373" alt="screen shot 2018-10-03 at 2 14 23 pm" src="https://user-images.githubusercontent.com/22392606/46395575-fe08d600-c716-11e8-86f4-bf3448db82f3.png">

**Comment by jakubmisek** [comment]
This issue is caused when you have references to `Peachpie.***` of various versions across your solution. All the versions of `Peachpie.***` libraries must be exactly the same.

**Comment by gordon-matt** [comment]
@jakubmisek Thanks for your recent PR which I guess should solve this issue and allow people to update the PeachPie libraries without this error. I will be releasing a new NuGet package soon - I just want to make a couple more changes first, including updating the demo project to use the new TinyMCE v5.0.4 before that.

**Comment by jakubmisek** [comment]
nice :) looking forward to it!

**Comment by jakubmisek** [comment]
suggesting to close the issue :)

**Comment by gordon-matt** [comment]
> 
> 
> suggesting to close the issue :)

I've been super busy for months now.. so haven't had time to deal with this. Will get around to it at some point.  :-)
