### ISSUE TITLE
upload error 

### ISSUE THREAD

**Issue by RenMen** [gordon-matt/peachpie-responsive-file-manager#17]
when try to upload file other than jpg,png,gif the below module throws null error exception @ /* if (!empty($extensions)) */

`protected function fix_file_extension($file_path, $name, $size, $type, $error,
            $index, $content_range) {
        // Add missing file extension for known image types:
        if (strpos($name, '.') === false &&
                preg_match('/^image\/(gif|jpe?g|png)/', $type, $matches)) {
            $name .= '.'.$matches[1];
        }
        if ($this->options['correct_image_extensions']) {
            switch ($this->imagetype($file_path)) {
                case self::IMAGETYPE_JPEG:
                    $extensions = array('jpg', 'jpeg');
                    break;
                case self::IMAGETYPE_PNG:
                    $extensions = array('png');
                    break;
                case self::IMAGETYPE_GIF:
                    $extensions = array('gif');
                    break;
            }
            // Adjust incorrect image file extensions:
            if ( isset($extensions)) {   //!empty is throwing null expception if try to upload jpg,png,gif`
                $parts = explode('.', $name);
                $extIndex = count($parts) - 1;
                $ext = strtolower(@$parts[$extIndex]);
                if (!in_array($ext, $extensions)) {
                    $parts[$extIndex] = $extensions[0];
                    $name = implode('.', $parts);
                }
            }
        }
        return $name;
    }`

**Comment by jakubmisek** [comment]
this has been fixed with the pull request https://github.com/gordon-matt/peachpie-responsive-file-manager/pull/16

**Comment by gordon-matt** [comment]
PR #16 is merged. But waiting on issue #18 to be resolved first before releasing new packages.
