### ISSUE TITLE
Not working in .NETFramework,Version=v4.6.1

### ISSUE THREAD

**Issue by Surenthiran** [gordon-matt/peachpie-responsive-file-manager#19]
Could not install package 'ResponsiveFileManager.AspNetCore 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by gordon-matt** [comment]
This file manager is for .NET Core only.. not the old .NET Framework. However, you can use my old project for MVC 5: [ResponsiveFileManagerMVC](https://github.com/gordon-matt/ResponsiveFileManagerMVC)
