### ISSUE TITLE
using responsive file manager with angular 13

### ISSUE THREAD

**Issue by Maryamkhn** [gordon-matt/peachpie-responsive-file-manager#24]
Dear Gordon,
In my project, I used .NET Core to act as an API backend and an Angular CLI project to act as a UI. I installed the file manager using NuGet but I'm confused about how to use it in CKEditor from angular and connect it to the backend. Can you please help me?

**Comment by gordon-matt** [comment]
You can check Responsive File Manager's [documentation](https://www.responsivefilemanager.com/#documentation-section) for that. But to help you, I added a new [demo page](https://github.com/gordon-matt/peachpie-responsive-file-manager/blob/master/WebApplication/Views/Home/CKEditor.cshtml).

By the way, CKEditor has its own file manager (CKFinder).. so maybe you would not need this file manager anyway? Here is the documentation:

[CKFinder for CKEditor4](https://ckeditor.com/docs/ckeditor4/latest/examples/image.html)

[CKFinder for CKEditor5](https://ckeditor.com/docs/ckeditor5/latest/features/images/image-upload/ckfinder.html#full-integration)

**Comment by Maryamkhn** [comment]
Many thanks for your response. 
Unfortunately, CKFinder is not compatible with .net core.
