### ISSUE TITLE
can't load file manager

### ISSUE THREAD

**Issue by Antonyab** [gordon-matt/peachpie-responsive-file-manager#26]
Hello, 

I didn't understand how I can call the file manager in my app.

I installaed the ResponsiveFileManager.AspNetCore NuGet package and I did all the steps mentioned in the doc.

But it is not mention how I can configure the filemanager to be called in a view for exemple. 

Can anyone help me with this please?

thank you in advance.

**Comment by gordon-matt** [comment]
You missed the part about looking at one of the demo pages.. You can find several examples in `/WebApplication/Views/Home`

**Comment by Antonyab** [comment]
Thank you very much for the help ! 

Excellent job by the way :D
