### ISSUE TITLE
Tiny MCE 5 issue

### ISSUE THREAD

**Issue by endorbilisim** [gordon-matt/peachpie-responsive-file-manager#30]
its not working with version 5 due to Tiny MCE changes

**Comment by gordon-matt** [comment]
As per the README:

```
For TinyMCE integration, you will need to copy the plugin from this solution to your tinymce/plugins folder. Plugins for TinyMCE versions 4 and 5 can be found in /Misc/TinyMCE Plugin.
```

**Comment by endorbilisim** [comment]
Tinymce itself is not working, files need to be updated.

**Comment by gordon-matt** [comment]
It was working perfectly fine the last time I checked it. You're going to have to elaborate some more.. what exact version of TinyMCE are you using? What exactly have you done to try make it work? etc... and also if you can make a small sample app and put it up on GitHub somewhere, that will be helpful for me to take a look as well.

**Comment by endorbilisim** [comment]
After a few edits I completed the integration but when uploading images I get "Unexpected end of JSON input". Thumbnails are not visible even though the images have been uploaded. After solving the last problem, I will share a working version with you on Github.
