### ISSUE TITLE
Error: NullReferenceException

### ISSUE THREAD

**Issue by dinhvanluan** [gordon-matt/peachpie-responsive-file-manager#4]
Hi bro, I try config my project same your project and readme.md but i get error. You can help me. Sorry my english is very poor
![image](https://user-images.githubusercontent.com/25924786/58277774-b1b4f800-7dc4-11e9-82d5-c11104abe485.png)

**Comment by thebigkappa** [comment]
same problem

**Comment by luaandv** [comment]
> 
> 
> same problem

i fixed.
