### ISSUE TITLE
responsive file manager error 302

### ISSUE THREAD

**Issue by bshafiei-ir** [gordon-matt/peachpie-responsive-file-manager#5]
I'm using dotnet core 3, tinymce 5, and responsive file manager 9.
So when I want open file manager I get error 302 (Found) and redirect to 404 page.

![image](https://user-images.githubusercontent.com/19801131/69911780-c8a06b00-1435-11ea-90fa-3276e5e0acf1.png)

Here is error:

![image](https://user-images.githubusercontent.com/19801131/69911783-d0f8a600-1435-11ea-9bba-d86f342eb1a9.png)

**Comment by j-ghadiri** [comment]
Hi @gordon-matt 
I Upgrade This Project to ASP.NET Core 3.1 together Peachpie.AspNetCore.Web PackageReference to 0.9.600 version but don't work properly
I get this error 

![error Peachpie AspNetCore Web](https://user-images.githubusercontent.com/5592269/71344076-d64d9a00-2576-11ea-9e11-42fa5dfda612.png)


How to fix this error?

**Comment by gordon-matt** [comment]
The library was not working with .NET Core 3 until now. I have just published a new NuGet package, which targets .NET Core 3.1 / .NET Standard 2.1. Please see if that helps.
