### ISSUE TITLE
It not work on asp.net core 3.1, request the dialog.php return 404 error

### ISSUE THREAD

**Issue by viewtance** [gordon-matt/peachpie-responsive-file-manager#6]
I have installed the package and configured follow up your guideline, I am using tinymce 5 and alread integrated response file manager with it, but when open the file manager cannot access the dialog.php file, the server return 404 error, is there some thing missed?

**Comment by jakubmisek** [comment]
I suppose the package 1.1.0 only works for `netcoreapp2.0` since it copies its content files only to this target folder https://github.com/gordon-matt/peachpie-responsive-file-manager/blob/9cd541bbd73cf061b856bd772dbd12ea57b83f2b/Website/ResponsiveFileManager.msbuildproj#L23

**Comment by gordon-matt** [comment]
I have deployed a new package to NuGet that works with .NET Core 3.1 / .NET Standard 2.1

**Comment by thanhsonvnhp** [comment]
> I have deployed a new package to NuGet that works with .NET Core 3.1 / .NET Standard 2.1

I setup as you , but it error :( , i'm using tinymce 4 and PeachPie version 0.9.970
