### ISSUE TITLE
consider updating bower to npm

### ISSUE THREAD

**Issue by jakubmisek** [gordon-matt/peachpie-responsive-file-manager#7]
Since Bower is actually dead (https://stackoverflow.com/a/51831614/601646) and not resolved automatically upon project build, it makes sense to updgrade the WebApplication sample to npm

**Comment by gordon-matt** [comment]
I modified it to use [LibMan](https://docs.microsoft.com/en-us/aspnet/core/client-side/libman/libman-vs?view=aspnetcore-3.1)
